[
  {
    "id": 1,
    "title": "HIPHOP誕生",
    "description": "ブロンクスでブロックパーティー文化からHIPHOPが誕生",
    "genre": "HIPHOP",
    "year": 1970,
    "lat": 40.84531783703358,
    "lng": -73.86613314825985,
    "people": ["グランド・マスター・フラッシュ"],
    "song": "Rapper's Delight",
    "song_url": "https://www.youtube.com/watch?v=rKTUAESacQM"
  },
  {
    "id": 2,
    "title": "DJ Kool Hercのブレイクビーツ",
    "description": "ブレイクビーツ技法の確立",
    "genre": "HIPHOP",
    "year": 1973,
    "lat": 40.8448,
    "lng": -73.8648,
    "people": ["DJ Kool Herc"],
    "song": "Apache",
    "song_url": "https://www.youtube.com/watch?v=WY-Z6wm6TMQ"
  },
  {
    "id": 3,
    "title": "Sugarhill Records設立",
    "description": "HIPHOP初の商業的成功",
    "genre": "HIPHOP",
    "year": 1979,
    "lat": 40.7128,
    "lng": -74.0060,
    "people": ["Sylvia Robinson"],
    "song": "Rapper's Delight",
    "song_url": "https://www.youtube.com/watch?v=rKTUAESacQM"
  },
  {
    "id": 4,
    "title": "The Message",
    "description": "社会問題を扱うリリックの確立",
    "genre": "HIPHOP",
    "year": 1982,
    "lat": 40.7306,
    "lng": -73.9352,
    "people": ["Grandmaster Flash"],
    "song": "The Message",
    "song_url": "https://www.youtube.com/watch?v=PobrSpMwKk4"
  },
  {
    "id": 5,
    "title": "Run-D.M.C.登場",
    "description": "ストリートとHIPHOPの融合",
    "genre": "HIPHOP",
    "year": 1984,
    "lat": 40.6782,
    "lng": -73.9442,
    "people": ["Run-D.M.C."],
    "song": "It's Like That",
    "song_url": "https://www.youtube.com/watch?v=TLGWQfK-6DY"
  },
  {
    "id": 6,
    "title": "Public Enemy台頭",
    "description": "政治的メッセージの象徴",
    "genre": "HIPHOP",
    "year": 1988,
    "lat": 40.7420,
    "lng": -73.7694,
    "people": ["Chuck D"],
    "song": "Fight the Power",
    "song_url": "https://www.youtube.com/watch?v=mmo3HFa2vjg"
  },
  {
    "id": 7,
    "title": "N.W.A",
    "description": "ギャングスタラップ誕生",
    "genre": "HIPHOP",
    "year": 1988,
    "lat": 33.9425,
    "lng": -118.4081,
    "people": ["N.W.A"],
    "song": "Straight Outta Compton",
    "song_url": "https://www.youtube.com/watch?v=TMZi25Pq3T8"
  },
  {
    "id": 8,
    "title": "De La Soul",
    "description": "オルタナティブHIPHOP",
    "genre": "HIPHOP",
    "year": 1989,
    "lat": 40.7934,
    "lng": -73.4151,
    "people": ["De La Soul"],
    "song": "Me Myself and I",
    "song_url": "https://www.youtube.com/watch?v=zR9AlcgL6_0"
  },
  {
    "id": 9,
    "title": "Wu-Tang Clan",
    "description": "東海岸黄金期の象徴",
    "genre": "HIPHOP",
    "year": 1993,
    "lat": 40.5795,
    "lng": -74.1502,
    "people": ["Wu-Tang Clan"],
    "song": "C.R.E.A.M.",
    "song_url": "https://www.youtube.com/watch?v=PBwAxmrE194"
  },
  {
    "id": 10,
    "title": "Nas Illmatic",
    "description": "史上最高峰のリリックアルバム",
    "genre": "HIPHOP",
    "year": 1994,
    "lat": 40.7506,
    "lng": -73.9935,
    "people": ["Nas"],
    "song": "N.Y. State of Mind",
    "song_url": "https://www.youtube.com/watch?v=hI8A14Qcv68"
  },
  {
    "id": 11,
    "title": "2Pac",
    "description": "西海岸と詩的リリック",
    "genre": "HIPHOP",
    "year": 1995,
    "lat": 34.0522,
    "lng": -118.2437,
    "people": ["2Pac"],
    "song": "California Love",
    "song_url": "https://www.youtube.com/watch?v=omfz62qu_Bc"
  },
  {
    "id": 12,
    "title": "Biggie",
    "description": "NYラップの完成形",
    "genre": "HIPHOP",
    "year": 1995,
    "lat": 40.6782,
    "lng": -73.9442,
    "people": ["Notorious B.I.G."],
    "song": "Juicy",
    "song_url": "https://www.youtube.com/watch?v=_JZom_gVfuw"
  },
  {
    "id": 13,
    "title": "Jay-Z デビュー",
    "description": "ビジネスHIPHOP",
    "genre": "HIPHOP",
    "year": 1996,
    "lat": 40.6839,
    "lng": -73.9754,
    "people": ["Jay-Z"],
    "song": "Dead Presidents",
    "song_url": "https://www.youtube.com/watch?v=F9W3n6zKX7Q"
  },
  {
    "id": 14,
    "title": "Eminem",
    "description": "白人ラッパーのブレイク",
    "genre": "HIPHOP",
    "year": 1999,
    "lat": 42.3314,
    "lng": -83.0458,
    "people": ["Eminem"],
    "song": "My Name Is",
    "song_url": "https://www.youtube.com/watch?v=sNPnbI1arSE"
  },
  {
    "id": 15,
    "title": "OutKast",
    "description": "南部HIPHOPの確立",
    "genre": "HIPHOP",
    "year": 2000,
    "lat": 33.7490,
    "lng": -84.3880,
    "people": ["OutKast"],
    "song": "Ms. Jackson",
    "song_url": "https://www.youtube.com/watch?v=MYxAiK6VnXw"
  },
  {
    "id": 16,
    "title": "Kanye West",
    "description": "プロデューサー主導HIPHOP",
    "genre": "HIPHOP",
    "year": 2004,
    "lat": 41.8781,
    "lng": -87.6298,
    "people": ["Kanye West"],
    "song": "Jesus Walks",
    "song_url": "https://www.youtube.com/watch?v=MYF7H_fpc-g"
  },
  {
    "id": 17,
    "title": "50 Cent",
    "description": "ストリート回帰",
    "genre": "HIPHOP",
    "year": 2003,
    "lat": 40.7282,
    "lng": -73.7949,
    "people": ["50 Cent"],
    "song": "In Da Club",
    "song_url": "https://www.youtube.com/watch?v=5qm8PH4xAss"
  },
  {
    "id": 18,
    "title": "Lil Wayne",
    "description": "ミックステープ文化",
    "genre": "HIPHOP",
    "year": 2008,
    "lat": 29.9511,
    "lng": -90.0715,
    "people": ["Lil Wayne"],
    "song": "A Milli",
    "song_url": "https://www.youtube.com/watch?v=1Vf4mMCpNY0"
  },
  {
    "id": 19,
    "title": "Trap Music",
    "description": "トラップの世界化",
    "genre": "HIPHOP",
    "year": 2010,
    "lat": 33.4484,
    "lng": -112.0740,
    "people": ["Gucci Mane"],
    "song": "Lemonade",
    "song_url": "https://www.youtube.com/watch?v=H6Q4s_ZdvAQ"
  },
  {
    "id": 20,
    "title": "Drake",
    "description": "メロディックラップ",
    "genre": "HIPHOP",
    "year": 2011,
    "lat": 43.6532,
    "lng": -79.3832,
    "people": ["Drake"],
    "song": "Take Care",
    "song_url": "https://www.youtube.com/watch?v=-zzP29emgpg"
  },

  {
    "id": 21,
    "title": "Kendrick Lamar",
    "description": "文学的HIPHOP",
    "genre": "HIPHOP",
    "year": 2015,
    "lat": 34.0522,
    "lng": -118.2437,
    "people": ["Kendrick Lamar"],
    "song": "Alright",
    "song_url": "https://www.youtube.com/watch?v=Z-48u_uWMHY"
  },
  {
    "id": 22,
    "title": "Future",
    "description": "トラップ×オートチューン",
    "genre": "HIPHOP",
    "year": 2015,
    "lat": 33.7490,
    "lng": -84.3880,
    "people": ["Future"],
    "song": "March Madness",
    "song_url": "https://www.youtube.com/watch?v=YG8kZmj5kMg"
  },
  {
    "id": 23,
    "title": "SoundCloud Rap",
    "description": "DIY世代の台頭",
    "genre": "HIPHOP",
    "year": 2016,
    "lat": 37.7749,
    "lng": -122.4194,
    "people": ["XXXTENTACION"],
    "song": "Look At Me!",
    "song_url": "https://www.youtube.com/watch?v=wJGcwEv7838"
  },
  {
    "id": 24,
    "title": "Migos",
    "description": "トリプレットフロー",
    "genre": "HIPHOP",
    "year": 2016,
    "lat": 33.7490,
    "lng": -84.3880,
    "people": ["Migos"],
    "song": "Bad and Boujee",
    "song_url": "https://www.youtube.com/watch?v=S-sJp1FfG7Q"
  },
  {
    "id": 25,
    "title": "日本語ラップ拡大",
    "description": "日本HIPHOPの市民権",
    "genre": "HIPHOP",
    "year": 2018,
    "lat": 35.6895,
    "lng": 139.6917,
    "people": ["KOHH"],
    "song": "Dirt Boys",
    "song_url": "https://www.youtube.com/watch?v=bdwzJYt1sS4"
  },
  {
    "id": 26,
    "title": "UK Drill",
    "description": "ロンドン発ドリル",
    "genre": "HIPHOP",
    "year": 2019,
    "lat": 51.5074,
    "lng": -0.1278,
    "people": ["Headie One"],
    "song": "18Hunna",
    "song_url": "https://www.youtube.com/watch?v=9xE9e8a5F6M"
  },
  {
    "id": 27,
    "title": "Pop Smoke",
    "description": "NY Drill",
    "genre": "HIPHOP",
    "year": 2020,
    "lat": 40.6782,
    "lng": -73.9442,
    "people": ["Pop Smoke"],
    "song": "Dior",
    "song_url": "https://www.youtube.com/watch?v=oorVWW9ywG0"
  },
  {
    "id": 28,
    "title": "Playboi Carti",
    "description": "実験的HIPHOP",
    "genre": "HIPHOP",
    "year": 2020,
    "lat": 33.7490,
    "lng": -84.3880,
    "people": ["Playboi Carti"],
    "song": "Sky",
    "song_url": "https://www.youtube.com/watch?v=KnumAWWWgUE"
  },
  {
    "id": 29,
    "title": "Griselda",
    "description": "BoomBap復権",
    "genre": "HIPHOP",
    "year": 2021,
    "lat": 42.8864,
    "lng": -78.8784,
    "people": ["Westside Gunn"],
    "song": "Dr. Birds",
    "song_url": "https://www.youtube.com/watch?v=5yq9Yp8G1N4"
  },
  {
    "id": 30,
    "title": "Female MC台頭",
    "description": "女性ラッパーの時代",
    "genre": "HIPHOP",
    "year": 2021,
    "lat": 29.7604,
    "lng": -95.3698,
    "people": ["Megan Thee Stallion"],
    "song": "Savage",
    "song_url": "https://www.youtube.com/watch?v=eJEKHdvntPI"
  },
  {
    "id": 31,
    "title": "Yeat",
    "description": "新世代トラップ",
    "genre": "HIPHOP",
    "year": 2022,
    "lat": 45.5152,
    "lng": -122.6784,
    "people": ["Yeat"],
    "song": "Money So Big",
    "song_url": "https://www.youtube.com/watch?v=Y-PoR4gEJ0o"
  },
  {
    "id": 32,
    "title": "Central Cee",
    "description": "UK Drillの世界化",
    "genre": "HIPHOP",
    "year": 2022,
    "lat": 51.5074,
    "lng": -0.1278,
    "people": ["Central Cee"],
    "song": "Doja",
    "song_url": "https://www.youtube.com/watch?v=_VuJA-VQRcY"
  },
  {
    "id": 33,
    "title": "AI × HIPHOP",
    "description": "制作手法の変革",
    "genre": "HIPHOP",
    "year": 2023,
    "lat": 37.7749,
    "lng": -122.4194,
    "people": ["世界中のプロデューサー"],
    "song": "—",
    "song_url": "https://www.youtube.com"
  },
  {
    "id": 34,
    "title": "アジアHIPHOP拡大",
    "description": "グローバル化",
    "genre": "HIPHOP",
    "year": 2023,
    "lat": 37.5665,
    "lng": 126.9780,
    "people": ["Jay Park"],
    "song": "Mommae",
    "song_url": "https://www.youtube.com/watch?v=gx_mg-1WhWw"
  },
  {
    "id": 35,
    "title": "Africa Drill",
    "description": "アフリカ発ドリル",
    "genre": "HIPHOP",
    "year": 2024,
    "lat": 6.5244,
    "lng": 3.3792,
    "people": ["ODUMODUBLVCK"],
    "song": "Declan Rice",
    "song_url": "https://www.youtube.com/watch?v=lgZpM0Q7Fcg"
  },
  {
    "id": 36,
    "title": "Virtual Rapper",
    "description": "仮想アーティスト",
    "genre": "HIPHOP",
    "year": 2024,
    "lat": 35.6895,
    "lng": 139.6917,
    "people": ["バーチャルMC"],
    "song": "—",
    "song_url": "https://www.youtube.com"
  },
  {
    "id": 37,
    "title": "Indie HipHop拡張",
    "description": "セルフプロデュース",
    "genre": "HIPHOP",
    "year": 2025,
    "lat": 34.0522,
    "lng": -118.2437,
    "people": ["Independent Artists"],
    "song": "—",
    "song_url": "https://www.youtube.com"
  },
  {
    "id": 38,
    "title": "ライブ配信文化",
    "description": "HIPHOPの新体験",
    "genre": "HIPHOP",
    "year": 2025,
    "lat": 37.7749,
    "lng": -122.4194,
    "people": ["Streaming Artists"],
    "song": "—",
    "song_url": "https://www.youtube.com"
  },
  {
    "id": 39,
    "title": "ジャンル融合",
    "description": "Rock / Reggae / Jazz",
    "genre": "HIPHOP",
    "year": 2026,
    "lat": 51.1657,
    "lng": 10.4515,
    "people": ["Global Artists"],
    "song": "—",
    "song_url": "https://www.youtube.com"
  },
  {
    "id": 40,
    "title": "現代HIPHOP",
    "description": "多様性と進化",
    "genre": "HIPHOP",
    "year": 2026,
    "lat": 34.0522,
    "lng": -118.2437,
    "people": ["世界中のアーティスト"],
    "song": "TBD",
    "song_url": "https://www.youtube.com"
  }
]
